/*
=========================================================
BondStats Finora
Printable Report Export
Version 1.0.0
=========================================================
*/

export function printCurrentWorkspace(){

window.print();

}

export function createPrintableReport(options={}){

const reportWindow=window.open("","_blank","noopener,noreferrer");

if(!reportWindow){

return false;

}

const title=options.title||"BondStats Finora Report";

const sections=options.sections||[];

reportWindow.document.write(`

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${escapeHTML(title)}</title>
<style>
body{
font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;
color:#111;
background:white;
padding:40px;
line-height:1.6;
}
h1{
font-size:34px;
margin-bottom:6px;
}
h2{
font-size:22px;
margin-top:32px;
border-bottom:1px solid #ddd;
padding-bottom:8px;
}
p{
color:#444;
}
table{
width:100%;
border-collapse:collapse;
margin-top:16px;
}
th,td{
border:1px solid #ddd;
padding:10px;
text-align:left;
font-size:13px;
}
th{
background:#f5f5f5;
}
.meta{
color:#666;
margin-bottom:32px;
}
.disclaimer{
margin-top:40px;
padding-top:20px;
border-top:1px solid #ddd;
font-size:12px;
color:#666;
}
@media print{
body{
padding:24px;
}
}
</style>
</head>
<body>

<h1>${escapeHTML(title)}</h1>
<div class="meta">
Generated by BondStats Finora • ${new Date().toLocaleString()}
</div>

${sections.map(section=>renderSection(section)).join("")}

<div class="disclaimer">
This report is for educational financial intelligence only and does not constitute financial advice.
</div>

<script>
window.onload=function(){
setTimeout(function(){
window.print();
},300);
};
</script>

</body>
</html>

`);

reportWindow.document.close();

return true;

}

export function portfolioReport(assets=[],analytics={}){

return createPrintableReport({

title:"BondStats Finora Portfolio Report",

sections:[

{
title:"Portfolio Summary",
type:"keyValue",
data:{
"Assets":assets.length,
"Total Allocation":`${analytics.totalAllocation?.toFixed?.(1)||0}%`,
"Health Score":analytics.healthScore||0,
"Diversification":analytics.diversificationScore||0,
"Weighted Risk":analytics.weightedRisk?.toFixed?.(2)||0
}
},

{
title:"Assets",
type:"table",
columns:[
"Name",
"Type",
"Allocation",
"Region",
"Sector",
"Currency",
"Risk"
],
rows:assets.map(asset=>[
asset.name,
asset.type,
`${Number(asset.allocation||0).toFixed(2)}%`,
asset.region,
asset.sector,
asset.currency,
asset.risk
])
},

{
title:"Analytics",
type:"keyValue",
data:flattenAnalytics(analytics)
}

]

});

}

export function researchReport(notes=[],bookmarks=[]){

return createPrintableReport({

title:"BondStats Finora Research Report",

sections:[

{
title:"Research Notes",
type:"table",
columns:[
"Title",
"Body",
"Tags",
"Pinned"
],
rows:notes.map(note=>[
note.title,
note.body,
(note.tags||[]).join(", "),
note.pinned?"Yes":"No"
])
},

{
title:"Bookmarks",
type:"table",
columns:[
"Title",
"Reference",
"Tags",
"Pinned"
],
rows:bookmarks.map(bookmark=>[
bookmark.title,
bookmark.reference,
(bookmark.tags||[]).join(", "),
bookmark.pinned?"Yes":"No"
])
}

]

});

}

export function briefReport(brief={}){

return createPrintableReport({

title:"BondStats Finora Daily Brief",

sections:[

{
title:"Brief Notes",
type:"text",
text:brief.notes||"No brief notes saved."
},

{
title:"Generated",
type:"keyValue",
data:{
"Last Generated":brief.lastGenerated||"Not saved"
}
}

]

});

}

function renderSection(section){

if(section.type==="table"){

return`

<h2>${escapeHTML(section.title)}</h2>

<table>

<thead>

<tr>

${section.columns.map(column=>`<th>${escapeHTML(column)}</th>`).join("")}

</tr>

</thead>

<tbody>

${section.rows.map(row=>`

<tr>

${row.map(cell=>`<td>${escapeHTML(cell)}</td>`).join("")}

</tr>

`).join("")}

</tbody>

</table>

`;

}

if(section.type==="keyValue"){

return`

<h2>${escapeHTML(section.title)}</h2>

<table>

<tbody>

${Object.entries(section.data).map(([key,value])=>`

<tr>

<th>${escapeHTML(key)}</th>

<td>${escapeHTML(value)}</td>

</tr>

`).join("")}

</tbody>

</table>

`;

}

return`

<h2>${escapeHTML(section.title)}</h2>

<p>${escapeHTML(section.text||"")}</p>

`;

}

function flattenAnalytics(analytics={}){

const result={};

Object.entries(analytics).forEach(([key,value])=>{

if(value&&typeof value==="object"&&!Array.isArray(value)){

Object.entries(value).forEach(([innerKey,innerValue])=>{

if(typeof innerValue!=="object"){

result[`${key}.${innerKey}`]=innerValue;

}

});

}else{

result[key]=value;

}

});

return result;

}

function escapeHTML(value){

return String(value??"").replace(/[&<>"']/g,char=>({

"&":"&amp;",
"<":"&lt;",
">":"&gt;",
'"':"&quot;",
"'":"&#039;"

}[char]));

}
